// Enhanced Default Equipment for New Users
// Auto-generated by load_comprehensive_equipment.py

const ENHANCED_DEFAULT_EQUIPMENT = [
  {
    "id": 1,
    "name": "Chef's Knife",
    "category": "Cutlery",
    "brand": "Standard",
    "model": "8-inch",
    "location": "Kitchen",
    "status": "Active",
    "notes": "Primary cutting tool - keep sharp",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-10-24T22:59:42.041712"
  },
  {
    "id": 2,
    "name": "Cutting Board",
    "category": "Prep Equipment",
    "brand": "Standard",
    "model": "Large Wooden",
    "location": "Prep Station",
    "status": "Active",
    "notes": "Sanitize regularly",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-09-24T22:59:42.041740"
  },
  {
    "id": 3,
    "name": "Measuring Cups",
    "category": "Tools",
    "brand": "Standard",
    "model": "Set",
    "location": "Prep Station",
    "status": "Active",
    "notes": "Dry and liquid measures",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-09-24T22:59:42.041748"
  },
  {
    "id": 4,
    "name": "Measuring Spoons",
    "category": "Tools",
    "brand": "Standard",
    "model": "Set",
    "location": "Prep Station",
    "status": "Active",
    "notes": "Small measurements",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-09-24T22:59:42.041753"
  },
  {
    "id": 5,
    "name": "Mixing Bowls",
    "category": "Prep Equipment",
    "brand": "Standard",
    "model": "Set of 3",
    "location": "Prep Station",
    "status": "Active",
    "notes": "Various sizes",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-09-24T22:59:42.041758"
  },
  {
    "id": 6,
    "name": "Whisk",
    "category": "Tools",
    "brand": "Standard",
    "model": "Balloon",
    "location": "Utensil Drawer",
    "status": "Active",
    "notes": "For mixing and aerating",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-09-24T22:59:42.041767"
  },
  {
    "id": 7,
    "name": "Spatula",
    "category": "Tools",
    "brand": "Standard",
    "model": "Rubber",
    "location": "Utensil Drawer",
    "status": "Active",
    "notes": "For scraping and folding",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-09-24T22:59:42.041771"
  },
  {
    "id": 8,
    "name": "Tongs",
    "category": "Tools",
    "brand": "Standard",
    "model": "12-inch",
    "location": "Utensil Drawer",
    "status": "Active",
    "notes": "For handling hot items",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-09-24T22:59:42.041775"
  },
  {
    "id": 9,
    "name": "Colander",
    "category": "Tools",
    "brand": "Standard",
    "model": "Large",
    "location": "Prep Station",
    "status": "Active",
    "notes": "For draining pasta and vegetables",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-09-24T22:59:42.041778"
  },
  {
    "id": 10,
    "name": "Digital Scale",
    "category": "Tools",
    "brand": "Standard",
    "model": "Kitchen Scale",
    "location": "Prep Station",
    "status": "Active",
    "notes": "For precise measurements",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-09-24T22:59:42.041782"
  },
  {
    "id": 11,
    "name": "Saucepan",
    "category": "Cookware",
    "brand": "Standard",
    "model": "2-Qt",
    "location": "Stove Area",
    "status": "Active",
    "notes": "For sauces and small quantities",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-08-25T22:59:42.041787"
  },
  {
    "id": 12,
    "name": "Frying Pan",
    "category": "Cookware",
    "brand": "Standard",
    "model": "10-inch",
    "location": "Stove Area",
    "status": "Active",
    "notes": "Non-stick preferred",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-08-25T22:59:42.041791"
  },
  {
    "id": 13,
    "name": "Baking Sheet",
    "category": "Cookware",
    "brand": "Standard",
    "model": "Half Sheet",
    "location": "Oven Area",
    "status": "Active",
    "notes": "For roasting and baking",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-08-25T22:59:42.041795"
  },
  {
    "id": 14,
    "name": "Grater",
    "category": "Tools",
    "brand": "Standard",
    "model": "Box Grater",
    "location": "Prep Station",
    "status": "Active",
    "notes": "Multiple grating surfaces",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-09-24T22:59:42.041799"
  },
  {
    "id": 15,
    "name": "Peeler",
    "category": "Tools",
    "brand": "Standard",
    "model": "Swivel",
    "location": "Utensil Drawer",
    "status": "Active",
    "notes": "For vegetables and fruits",
    "last_maintenance": "2025-07-26T22:59:42.041673",
    "next_maintenance": "2025-09-24T22:59:42.041802"
  }
];

// Export for use in userDataManager.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ENHANCED_DEFAULT_EQUIPMENT;
}

// Make available globally in browser
if (typeof window !== 'undefined') {
    window.ENHANCED_DEFAULT_EQUIPMENT = ENHANCED_DEFAULT_EQUIPMENT;
}
