name: Automated Dependency Updates

on:
  schedule:
    # Run every Monday at 2 AM UTC
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Update npm dependencies
      run: |
        npm update
        npm audit fix --force
        
    - name: Check for security vulnerabilities
      run: |
        npm audit --audit-level moderate
        
    - name: Run tests with updated dependencies
      run: |
        npm ci
        npm test
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'Automated Dependency Updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated updates to project dependencies.
          
          ### Changes Made:
          - Updated npm packages to latest compatible versions
          - Applied security fixes from npm audit
          - Verified all tests pass with updated dependencies
          
          ### Security Notes:
          - All security vulnerabilities have been addressed
          - Dependencies are updated to latest secure versions
          
          ### Testing:
          - ✅ All existing tests pass
          - ✅ No breaking changes detected
          - ✅ Security scan completed successfully
          
          **Note**: Please review the changes and test thoroughly before merging.
        branch: automated-dependency-updates
        delete-branch: true
        
    - name: Comment on PR
      uses: actions/github-script@v7
      if: success()
      with:
        script: |
          const { data: pr } = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: `${context.repo.owner}:automated-dependency-updates`,
            state: 'open'
          });
          
          if (pr.length > 0) {
            await github.rest.issues.createComment({
              issue_number: pr[0].number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🤖 **Automated Dependency Update**
              
              This PR was created automatically by the dependency update workflow.
              
              ### Next Steps:
              1. Review the dependency changes
              2. Test the application locally
              3. Merge if everything looks good
              
              ### Dependencies Updated:
              - Check the file changes to see which packages were updated
              
              ### Security:
              - All security vulnerabilities have been addressed
              - Dependencies are now up to date`
            });
          }
          
    - name: Notify on failure
      uses: 8398a7/action-slack@v3
      if: failure()
      with:
        status: failure
        channel: '#dev-alerts'
        text: 'Dependency update workflow failed'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
